#!/bin/bash

if [ $# -eq 1 ]; then
  g++ cp.cpp -std=c++20
  if [ $? -ne 0 ]; then
    echo -e "\033[0;31mCompilation failed.\033[0m"
    exit 1
  fi
fi

./a.out < in > out1

if diff -w out1 out2 > /dev/null; then
  echo -e "\033[0;32mOutput matches! ✅\033[0m"
else
  echo -e "\033[0;31mOutput does NOT match! ❌\033[0m"
  echo "Differences (word-level):"
  wdiff out2 out1 | sed -e "s/\[\-/$(tput setaf 1)/g" \
                      -e "s/-\]/$(tput sgr0)/g" \
                      -e "s/{+/$(tput setaf 2)/g" \
                      -e "s/+}/$(tput sgr0)/g"

fi
